name: Semantic release

on:
  push:
    branches:
      - main
jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.19.0
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn build
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
